dist: xenial
sudo: true
language: python
matrix:
  include:
  - python: 3.7
    name: "Py37-skl020"
    env: sklearnc="==0.20"
  - python: 3.7
    name: "Py37-skl021+"
    env: sklearnc=">=0.21"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-6 g++-6
  - pip install -r requirements.txt
  - pip install pyquickhelper --no-deps
  - pip install scikit-learn$sklearnc
  - python -c "import sklearn;print(sklearn.__version__)"
before_script:
  - python setup.py build_ext --inplace
script:
    - python setup.py unittests
